
// This code is generated by emlearn

#include <eml_distance.h>


static const float EllipticEnvelope_means[2] = { -2.955444f, 0.025547f };

static const float EllipticEnvelope_precisions[4] = { 0.785820f, -0.309613f, -0.309613f, 0.509932f };
#include <stdio.h>

// Data definitions
static const EmlEllipticEnvelope EllipticEnvelope_classifier = {
  2,
  -4.604818593424524f,
  EllipticEnvelope_means,
  EllipticEnvelope_precisions
};

// Prediction function
float EllipticEnvelope_predict(const float *features, int n_features) {
  float dist = 0.0;
  const int class_ = eml_elliptic_envelope_predict(&EllipticEnvelope_classifier,
                                                  features, n_features, &dist);
  return dist;
}
